### PR TITLE
Convert doctests to django unittests and add travis-ci support

### PR DESCRIPTION
**Pull request by atugushev**
Hi! To make a project more comfortable for contributing I've made the following changes:

1. Add support of [Travis-ci](https://travis-ci.org/) and [Coveralls](https://coveralls.io/)
2. Convert all doctests to django unitests
3. Add new test runner
4. Drop unneeded django-testproject using
5. Fix a few bugs and python3 issues of incompatibility.

#### NOTE
To complete adding support of [travis-ci](https://travis-ci.org/) and [coveralls](https://coveralls.io/) @zyga should authorize and enable repo in settings.

Please, review PR. Thanks!

[Build Status](https://travis-ci.org/atugushev/django-pagination/) [Coverage Status](https://coveralls.io/github/atugushev/django-pagination?branch=master)

### CODE REVIEW

**Comment by zyga** [comment]
Wow, fantastic effort! It is my pleasure to merge this!

**Comment by atugushev** [comment]
Thank you very much!

BTW, would you mind closing fixed issues -- #16,  #30, #32, #33?

**Comment by zyga** [comment]
Done, thanks again @atugushev :)

**Comment by Gagaro** [comment]
Awesome, thanks! :+1:

**Pull request merged**
